services:

  database:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=Alterra@miniPR0ject#@!
      - MYSQL_DATABASE=tanam_backend
    ports:
      - 3306:3306

  app:
    image: haradakumiko/tanam-backend:latest
    restart: always
    depends_on:
       - database
    ports:
      - 1323:1323