name: TANAM BACKEND GITHUB ACTION

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "SSH, Build & Deploy"
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.KEY}}
          port: ${{secrets.PORT}}
          script: |
            
            cd /home/tanam-backend
            git pull origin main
            cp .env.local .env
            sed -i "s/DB_HOST=.*/DB_HOST=\"${{secrets.DB_HOST}}\"/" .env
            sed -i "s/DB_PORT=.*/DB_PORT=\"${{secrets.DB_PORT}}\"/" .env
            sed -i "s/DB_USERNAME=.*/DB_USERNAME=\"${{secrets.USERNAME}}\"/" .env
            sed -i "s/DB_PASSWORD=.*/DB_PASSWORD=\"${{secrets.DB_PASSWORD}}\"/" .env
            sed -i "s/DB_NAME=.*/DB_NAME=\"${{secrets.DB_NAME}}\"/" .env
            sed -i "s/CLIENT_KEY=.*/CLIENT_KEY=\"${{secrets.CLIENT_KEY}}\"/" .env
            sed -i "s/SERVER_KEY=.*/SERVER_KEY=\"${{secrets.SERVER_KEY}}\"/" .env
            sed -i "s/IRIS_KEY=.*/IRIS_KEY=\"${{secrets.IRIS_KEY}}\"/" .env
            sed -i "s/MERCHANT_ID=.*/MERCHANT_ID=\"${{secrets.MERCHANT_ID}}\"/" .env
            cd deploys
            docker compose down
            cd .. 
            docker image rm haradakumiko/tanam-backend:latest
            docker volume prune
            docker build -t haradakumiko/tanam-backend:latest --no-cache -f deploys/Dockerfile . 
            docker builder prune
            cd deploys 
            docker compose up -d